[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "music"
version = "1.2.0"
description = "Helper tools for music"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flask>=3.0.3",
]

[project.optional-dependencies]
media = [
    "matplotlib>=3.9.2",
    "numpy<2",
]
test = [
    "setuptools",
    "pytest",
    "ruff",
]

[project.scripts]
music-cli = "music.cli:main"
music-app = "music.app:main"

[tool.pytest.ini_options]
pythonpath = [
  "."
]