[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "music"
dynamic = ["version"]
description = "Helper tools for music"
readme = "README.md"
requires-python = ">=3.9,<3.14"
dependencies = [
    "flask>=3.0.3",
    "numpy<2",
    "scipy>=1.13.1",
]

[project.optional-dependencies]
media = [
    "matplotlib>=3.9.2",
]
test = [
    "setuptools",
    "pytest",
    "pytest-cov",
    "ruff",
    "ty",
    "tox-uv",
]

[project.scripts]
music-cli = "music.cli:main"
music-app = "music.app:main"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "_version.py"

[tool.tox]
env_list = ["py39", "py310", "py311", "py312", "py313"]
isolated_build = true

[tool.tox.env_run_base]
description = "Run test under {base_python}"
commands = [["pytest"], ["ruff", "check"]]

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "--cov=music"

[tool.coverage.run]
parallel = true
patch = ["subprocess"]

[tool.coverage.report]
fail_under = 90
omit = [
    "src/music/app.py",
    "src/music/cli.py",
]
