name: CI Build
run-name: Running CI build for branch ${{ github.ref_name }}
on: [pull_request]
permissions:
  contents: read
jobs:
  CI-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Python setup uv
        uses: astral-sh/setup-uv@v3.1.1
      - name: Clone repo
        uses: actions/checkout@v4
      - name: install tox
        run: uv tool install tox --with tox-uv
      - name: Tox tests
        run: tox
      - run: echo "This job's status is ${{ job.status }}."