name: CI Build
run-name: Running CI build for branch ${{ github.ref_name }}
on: [pull_request]
permissions:
  contents: read
jobs:
  CI-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Python setup uv
        uses: astral-sh/setup-uv@v3.1.1
      - uses: actions/checkout@v4
      - run: echo "Cloned ${{ github.repository }} repository to the runner."
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install the project
        run: uv sync --all-extras
      - name: Unit tests
        run: uv run pytest tests
      - name: Linting / formatting
        run: uv run ruff check
      - run: echo "This job's status is ${{ job.status }}."