name: CI Build
run-name: Running CI build for branch ${{ github.ref_name }}
on: [pull_request]
permissions:
  contents: read
jobs:
  CI-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Python setup uv
        uses: astral-sh/setup-uv@v3.1.1
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Infer version
        run: >
          VERSION=$(cat ${{github.workspace}}/src/music/__init__.py | cut -d '=' -f 2 | sed 's/"//g;s/^ *//g') &&
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Use version
        run: echo "version=${{ env.VERSION }}"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install the project
        run: uv sync --all-extras
      - name: Unit tests
        run: uv run pytest tests
      - name: Linting / formatting
        run: uv run ruff check
      - name: Typechecking
        run: uv run ty check
      - run: echo "This job's status is ${{ job.status }}."