name: CI Build
run-name: Running CI build for branch ${{ github.ref_name }}
on: [pull_request]
permissions:
  contents: read
jobs:
  CI-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Python setup uv
        uses: astral-sh/setup-uv@v3.1.1
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Install python
        run: uv python install 3.9 3.10 3.11 3.12
      - name: Install the project
        run: uv sync --all-extras
      - name: Tox tests
        run: uv run tox
      - run: echo "This job's status is ${{ job.status }}."